basic:
- compline: "mygit "
  expected: [init, st, status]

- compline: "mygit stat"
  expected: [status]

- compline: "mygit status -"
  expected: [--branch, --verbose, -b, -v]

- compline: "mygit init "
  expected: [--bare, another-dir, dir with spaces, dummy-dir]

- compline: "mygit st -"
  expected: [--branch, --verbose, -b, -v]

- compline: "mygit status --branch "
  expected: [dev, main]

- compline: "mygit status -b m"
  expected: [main]

- compline: "mygit init d"
  expected: [dir with spaces, dummy-dir]

- compline: "mygit init dummy-dir -"
  expected: [--bare]

static-values:
- compline: "mygit deploy st"
  expected: [staging]

interleaved:
- compline: "cli "
  expected: [clone]

- compline: "cli clone "
  expected: [--protocol, --verbose, -p, -v, source1, source2]

- compline: "cli clone -v "
  expected: [--protocol, --verbose, -p, -v, source1, source2]

- compline: "cli clone -v source1 "
  expected: [--protocol, --verbose, -p, -v, dest1, dest2]

- compline: "cli clone -v source1 -p "
  expected: [https, ssh]

- compline: "cli clone -v source1 -p ssh "
  expected: [--protocol, --verbose, -p, -v, dest1, dest2]
