#!/usr/bin/env bash
if [[ -n $ZSH_VERSION ]]; then
  autoload -U +X bashcompinit && bashcompinit
  autoload -U +X compinit && compinit
fi

# === COMPLETION SCRIPT START ===

# mygit completion                                         -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/bashly-framework/completely)
# Modifying it manually is not recommended

_mygit_completions_filter() {
  local words=("$@")
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()
  local want_options=0

  # words the user already typed (excluding the command itself)
  local used=()
  if ((COMP_CWORD > 1)); then
    used=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")
  fi

  # Completing an option: offer everything.
  # Completing a non-option: drop options and already-used words.
  [[ "${cur:0:1}" == "-" ]] && want_options=1
  for word in "${words[@]}"; do
    if ((!want_options)); then
      [[ "${word:0:1}" == "-" ]] && continue

      for u in "${used[@]}"; do
        if [[ "$u" == "$word" ]]; then
          continue 2
        fi
      done
    fi

    # compgen -W expects shell-escaped words in one space-delimited string.
    printf -v word '%q' "$word"
    result+=("$word")
  done

  echo "${result[*]}"
}

_mygit_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=()
  if ((COMP_CWORD > 0)); then
    compwords=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")
  fi
  local compline="${compwords[*]}"

  COMPREPLY=()

  case "$compline" in
    'status'*'--branch')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_mygit_completions_filter "$(git branch --format='%(refname:short)' 2>/dev/null)")" -- "$cur")
      ;;

    'status'*'-b')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_mygit_completions_filter "$(git branch --format='%(refname:short)' 2>/dev/null)")" -- "$cur")
      ;;

    'status'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_mygit_completions_filter "--help" "--verbose" "--branch" "-b")" -- "$cur")
      ;;

    'init'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -W "$(_mygit_completions_filter "--bare")" -- "$cur")
      ;;

    *)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_mygit_completions_filter "-h" "-v" "--help" "--version" "init" "status")" -- "$cur")
      ;;

  esac
} &&
  complete -F _mygit_completions mygit

# ex: filetype=sh


# === COMPLETION SCRIPT END ===

COMP_WORDS=( mygit st )
COMP_LINE="mygit st"
COMP_POINT=${#COMP_LINE}
COMP_CWORD=1

_mygit_completions
for suggestion in "${COMPREPLY[@]}"; do
  echo "$suggestion"
done

